In [12]:
import numpy as np
import pandas as pd

In [13]:
kmeans = pd.read_csv("./k_means(중구, 23, 6-10, k=3)_n.csv")
diff = pd.read_csv("./중구대여반납_거치대23_group_6_10.csv")

df = pd.merge(kmeans, diff, how='left', left_on=kmeans.index, right_on=diff.index)
df

,key_0,위도_x,경도_x,cluster,대여소번호,대여수,반납수,거치대수,(반납-대여)/거치대수,위도_y,경도_y,group
0,0,37.568050,126.969231,C,300,17,19,9,0.222222,37.568050,126.969231,많음
1,1,37.568878,126.977470,C,310,5,13,8,1.000000,37.568878,126.977470,많음
2,2,37.568527,126.982552,B,318,6,10,12,0.333333,37.568527,126.982552,많음
3,3,37.566223,126.983589,B,320,8,16,17,0.470588,37.566223,126.983589,많음
4,4,37.565464,126.984139,B,321,8,12,17,0.235294,37.565464,126.984139,많음
5,5,37.564476,126.986969,B,322,3,8,17,0.294118,37.564476,126.986969,많음
6,6,37.561340,126.980400,C,324,5,9,12,0.333333,37.561340,126.980400,많음
7,7,37.566383,126.987206,B,331,3,10,10,0.700000,37.566383,126.987205,많음
8,8,37.565990,126.987793,B,332,6,12,5,1.200000,37.565990,126.987793,많음
9,9,37.562618,126.992836,B,336,7,11,12,0.333333,37.562618,126.992836,많음
10,10,37.569183,127.009880,A,346,7,20,12,1.083333,37.569183,127.009880,많음
11,12,37.563229,126.974838,C,370,16,41,24,1.041667,37.563229,126.974838,많음
12,17,37.563866,127.002747,A,380,10,13,10,0.300000,37.563866,127.002747,많음
13,23,37.561390,126.995354,B,390,12,17,12,0.416667,37.561390,126.995354,많음
14,33,37.562111,126.970718,C,443,4,8,9,0.444444,37.562111,126.970718,많음
15,34,37.560154,126.974106,C,445,5,13,10,0.800000,37.560154,126.974106,많음
16,36,37.562214,126.980865,C,467,2,6,16,0.250000,37.562214,126.980866,많음
17,39,37.560360,126.982651,C,471,5,9,10,0.400000,37.560360,126.982651,많음
18,40,37.567871,126.988983,B,472,3,11,12,0.666667,37.567871,126.988983,많음
19,50,37.567616,126.987244,B,3013,3,20,10,1.700000,37.567616,126.987244,많음
20,51,37.562843,126.972618,C,4753,1,4,10,0.300000,37.562843,126.972618,많음
21,58,37.565990,126.984276,B,4775,2,8,10,0.600000,37.565990,126.984276,많음
22,64,37.566898,126.987740,B,4785,2,13,8,1.375000,37.566898,126.987740,많음
23,67,37.564308,127.006477,A,4793,3,10,10,0.700000,37.564308,127.006477,많음
24,68,37.566471,126.979256,C,4796,6,11,10,0.500000,37.566471,126.979256,많음
25,15,37.560474,127.014076,A,374,11,10,12,-0.083333,37.560474,127.014076,적음
26,16,37.556000,126.973358,C,379,10,9,9,-0.111111,37.556000,126.973358,적음
27,18,37.558533,127.006989,A,381,2,1,12,-0.083333,37.558533,127.006989,적음
28,19,37.555199,127.010048,A,382,13,6,9,-0.777778,37.555199,127.010048,적음
29,25,37.554108,126.965408,C,399,7,1,17,-0.352941,37.554108,126.965408,적음
30,32,37.556416,126.969193,C,442,2,1,20,-0.050000,37.556416,126.969193,적음
31,44,37.564430,127.009956,A,476,3,2,10,-0.100000,37.564430,127.009956,적음
32,49,37.555367,126.968643,C,826,16,5,22,-0.500000,37.555367,126.968643,적음
33,56,37.567017,126.976837,B,4768,26,19,12,-0.583333,37.567017,126.976837,적음
34,62,37.561573,126.968491,C,4782,2,1,10,-0.100000,37.561573,126.968491,적음
35,66,37.562527,126.998314,A,4792,8,6,10,-0.200000,37.562527,126.998314,적음

#  데이터 불러와서 C 군집만 추출

In [14]:
df = df[df.cluster == 'C']
df = df.sort_values(by='(반납-대여)/거치대수', ascending=False)
df

,key_0,위도_x,경도_x,cluster,대여소번호,대여수,반납수,거치대수,(반납-대여)/거치대수,위도_y,경도_y,group
11,12,37.563229,126.974838,C,370,16,41,24,1.041667,37.563229,126.974838,많음
1,1,37.568878,126.977470,C,310,5,13,8,1.000000,37.568878,126.977470,많음
15,34,37.560154,126.974106,C,445,5,13,10,0.800000,37.560154,126.974106,많음
24,68,37.566471,126.979256,C,4796,6,11,10,0.500000,37.566471,126.979256,많음
14,33,37.562111,126.970718,C,443,4,8,9,0.444444,37.562111,126.970718,많음
17,39,37.560360,126.982651,C,471,5,9,10,0.400000,37.560360,126.982651,많음
6,6,37.561340,126.980400,C,324,5,9,12,0.333333,37.561340,126.980400,많음
20,51,37.562843,126.972618,C,4753,1,4,10,0.300000,37.562843,126.972618,많음
16,36,37.562214,126.980865,C,467,2,6,16,0.250000,37.562214,126.980866,많음
0,0,37.568050,126.969231,C,300,17,19,9,0.222222,37.568050,126.969231,많음
30,32,37.556416,126.969193,C,442,2,1,20,-0.050000,37.556416,126.969193,적음
34,62,37.561573,126.968491,C,4782,2,1,10,-0.100000,37.561573,126.968491,적음
26,16,37.556000,126.973358,C,379,10,9,9,-0.111111,37.556000,126.973358,적음
29,25,37.554108,126.965408,C,399,7,1,17,-0.352941,37.554108,126.965408,적음
32,49,37.555367,126.968643,C,826,16,5,22,-0.500000,37.555367,126.968643,적음

In [15]:
df = df.reset_index()
df['node_num'] = range(1,16)
df

,index,key_0,위도_x,경도_x,cluster,대여소번호,대여수,반납수,거치대수,(반납-대여)/거치대수,위도_y,경도_y,group,node_num
0,11,12,37.563229,126.974838,C,370,16,41,24,1.041667,37.563229,126.974838,많음,1
1,1,1,37.568878,126.977470,C,310,5,13,8,1.000000,37.568878,126.977470,많음,2
2,15,34,37.560154,126.974106,C,445,5,13,10,0.800000,37.560154,126.974106,많음,3
3,24,68,37.566471,126.979256,C,4796,6,11,10,0.500000,37.566471,126.979256,많음,4
4,14,33,37.562111,126.970718,C,443,4,8,9,0.444444,37.562111,126.970718,많음,5
5,17,39,37.560360,126.982651,C,471,5,9,10,0.400000,37.560360,126.982651,많음,6
6,6,6,37.561340,126.980400,C,324,5,9,12,0.333333,37.561340,126.980400,많음,7
7,20,51,37.562843,126.972618,C,4753,1,4,10,0.300000,37.562843,126.972618,많음,8
8,16,36,37.562214,126.980865,C,467,2,6,16,0.250000,37.562214,126.980866,많음,9
9,0,0,37.568050,126.969231,C,300,17,19,9,0.222222,37.568050,126.969231,많음,10
10,30,32,37.556416,126.969193,C,442,2,1,20,-0.050000,37.556416,126.969193,적음,11
11,34,62,37.561573,126.968491,C,4782,2,1,10,-0.100000,37.561573,126.968491,적음,12
12,26,16,37.556000,126.973358,C,379,10,9,9,-0.111111,37.556000,126.973358,적음,13
13,29,25,37.554108,126.965408,C,399,7,1,17,-0.352941,37.554108,126.965408,적음,14
14,32,49,37.555367,126.968643,C,826,16,5,22,-0.500000,37.555367,126.968643,적음,15

# 대여소간 거리 계산해서 가중치 행렬 만들기

In [16]:
from haversine import haversine

dist = np.zeros((15,15))
for i in range(15):
    for j in range(i+1,15):
        distance = haversine((df.위도_x[i],df.경도_x[i]), (df.위도_x[j],df.경도_x[j]), unit='km')
        dist[i][j] = distance
        dist[j][i] = distance
df_dist = pd.DataFrame(dist)
df_dist

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.000000,0.669671,0.347929,0.530650,0.383819,0.758915,0.533308,0.200329,0.543104,0.729210,0.906414,0.589014,0.814332,1.311318,1.030763
1,0.669671,0.000000,1.014406,0.310481,0.959376,1.051496,0.877046,0.795745,0.799173,0.732025,1.566129,1.134135,1.477176,1.956503,1.691943
2,0.347929,1.014406,0.000000,0.836338,0.369461,0.753554,0.570280,0.326531,0.638343,0.977548,0.600311,0.519496,0.466604,1.019710,0.717808
3,0.530650,0.310481,0.836338,0.000000,0.895152,0.742504,0.579365,0.710632,0.494187,0.900860,1.427236,1.094052,1.275133,1.838418,1.549101
4,0.383819,0.959376,0.369461,0.895152,0.000000,1.069645,0.857675,0.186201,0.894474,0.673332,0.647420,0.205273,0.718265,1.005511,0.771929
5,0.758915,1.051496,0.753554,0.742504,1.069645,0.000000,0.226366,0.926435,0.259348,1.459597,1.264803,1.255417,0.951856,1.671369,1.353848
6,0.533308,0.877046,0.570280,0.579365,0.857675,0.226366,0.000000,0.706000,0.105444,1.235272,1.129542,1.050074,0.859042,1.546991,1.230957
7,0.200329,0.795745,0.326531,0.710632,0.186201,0.926435,0.706000,0.000000,0.730312,0.651445,0.775901,0.390270,0.763761,1.160792,0.902198
8,0.543104,0.799173,0.638343,0.494187,0.894474,0.259348,0.105444,0.730312,0.000000,1.213597,1.214254,1.093096,0.956747,1.633691,1.319256
9,0.729210,0.732025,0.977548,0.900860,0.673332,1.459597,1.235272,0.651445,1.213597,0.000000,1.293739,0.723197,1.388481,1.586549,1.411333
10,0.906414,1.566129,0.600311,1.427236,0.647420,1.264803,1.129542,0.775901,1.214254,1.293739,0.000000,0.576813,0.370108,0.420874,0.126299
11,0.589014,1.134135,0.519496,1.094052,0.205273,1.255417,1.050074,0.390270,1.093096,0.723197,0.576813,0.000000,0.753758,0.873445,0.690264
12,0.814332,1.477176,0.466604,1.275133,0.718265,0.951856,0.859042,0.763761,0.956747,1.388481,0.370108,0.753758,0.000000,0.731699,0.421555
13,1.311318,1.956503,1.019710,1.838418,1.005511,1.671369,1.546991,1.160792,1.633691,1.586549,0.420874,0.873445,0.731699,0.000000,0.317667
14,1.030763,1.691943,0.717808,1.549101,0.771929,1.353848,1.230957,0.902198,1.319256,1.411333,0.126299,0.690264,0.421555,0.317667,0.000000

# tsp

In [17]:
import copy

In [18]:
data = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
n = len(data)
all_sets = []
g = {}
p = []
node = [1]

In [19]:
def main():
    for x in range(1, n):
        g[x + 1, ()] = dist[x][0]

    get_minimum(1, (2,3,4,5,6,7,8,9,10,11,12,13,14,15))

    print('\n\nSolution to TSP: {1, ', end='')
    solution = p.pop()
    print(solution[1][0], end=', ')
    node.append(solution[1][0])
    for x in range(n - 2):
        for new_solution in p:
            if tuple(solution[1]) == new_solution[0]:
                solution = new_solution
                print(solution[1][0], end=', ')
                node.append(solution[1][0])
                break
    print('1}')
    return

In [20]:
def get_minimum(k, a):
    if (k, a) in g:
        # Already calculated Set g[%d, (%s)]=%d' % (k, str(a), g[k, a]))
        return g[k, a]

    values = []
    all_min = []
    for j in a:
        set_a = copy.deepcopy(list(a))
        set_a.remove(j)
        all_min.append([j, tuple(set_a)])
        result = get_minimum(j, tuple(set_a))
        values.append(dist[k-1][j-1] + result)

    # get minimun value from set as optimal solution for
    g[k, a] = min(values)
    p.append(((k, a), all_min[values.index(g[k, a])]))

    return g[k, a]

In [21]:
main()

Solution to TSP: {1, 8, 5, 12, 14, 15, 11, 13, 3, 7, 6, 9, 4, 2, 10, 1}

# 총거리 구하기

In [22]:
node.append(1)

dist_total = 0
for i in range(len(node)-1):
    dist_total += df_dist[node[i]-1][node[i+1]-1]
dist_total

6.067821536247934

In [23]:
len(df)

15

In [24]:
node

[1, 8, 5, 12, 14, 15, 11, 13, 3, 7, 6, 9, 4, 2, 10, 1]