In [12]:
import numpy as np
import pandas as pd

In [13]:
kmeans = pd.read_csv("./k_means(중구, 23, 6-10, k=5)_n.csv")
diff = pd.read_csv("./중구대여반납_거치대23_group_6_10.csv")

df = pd.merge(kmeans, diff, how='left', left_on=kmeans.index, right_on=diff.index)
df

,key_0,위도_x,경도_x,cluster,대여소번호,대여수,반납수,거치대수,(반납-대여)/거치대수,위도_y,경도_y,group
0,0,37.568050,126.969231,E,300,17,19,9,0.222222,37.568050,126.969231,많음
1,1,37.568878,126.977470,D,310,5,13,8,1.000000,37.568878,126.977470,많음
2,2,37.568527,126.982552,C,318,6,10,12,0.333333,37.568527,126.982552,많음
3,3,37.566223,126.983589,C,320,8,16,17,0.470588,37.566223,126.983589,많음
4,4,37.565464,126.984139,C,321,8,12,17,0.235294,37.565464,126.984139,많음
5,5,37.564476,126.986969,C,322,3,8,17,0.294118,37.564476,126.986969,많음
6,6,37.561340,126.980400,D,324,5,9,12,0.333333,37.561340,126.980400,많음
7,7,37.566383,126.987206,C,331,3,10,10,0.700000,37.566383,126.987205,많음
8,8,37.565990,126.987793,C,332,6,12,5,1.200000,37.565990,126.987793,많음
9,9,37.562618,126.992836,B,336,7,11,12,0.333333,37.562618,126.992836,많음
10,10,37.569183,127.009880,A,346,7,20,12,1.083333,37.569183,127.009880,많음
11,12,37.563229,126.974838,E,370,16,41,24,1.041667,37.563229,126.974838,많음
12,17,37.563866,127.002747,A,380,10,13,10,0.300000,37.563866,127.002747,많음
13,23,37.561390,126.995354,B,390,12,17,12,0.416667,37.561390,126.995354,많음
14,33,37.562111,126.970718,E,443,4,8,9,0.444444,37.562111,126.970718,많음
15,34,37.560154,126.974106,E,445,5,13,10,0.800000,37.560154,126.974106,많음
16,36,37.562214,126.980865,D,467,2,6,16,0.250000,37.562214,126.980866,많음
17,39,37.560360,126.982651,D,471,5,9,10,0.400000,37.560360,126.982651,많음
18,40,37.567871,126.988983,C,472,3,11,12,0.666667,37.567871,126.988983,많음
19,50,37.567616,126.987244,C,3013,3,20,10,1.700000,37.567616,126.987244,많음
20,51,37.562843,126.972618,E,4753,1,4,10,0.300000,37.562843,126.972618,많음
21,58,37.565990,126.984276,C,4775,2,8,10,0.600000,37.565990,126.984276,많음
22,64,37.566898,126.987740,C,4785,2,13,8,1.375000,37.566898,126.987740,많음
23,67,37.564308,127.006477,A,4793,3,10,10,0.700000,37.564308,127.006477,많음
24,68,37.566471,126.979256,D,4796,6,11,10,0.500000,37.566471,126.979256,많음
25,15,37.560474,127.014076,A,374,11,10,12,-0.083333,37.560474,127.014076,적음
26,16,37.556000,126.973358,E,379,10,9,9,-0.111111,37.556000,126.973358,적음
27,18,37.558533,127.006989,B,381,2,1,12,-0.083333,37.558533,127.006989,적음
28,19,37.555199,127.010048,B,382,13,6,9,-0.777778,37.555199,127.010048,적음
29,25,37.554108,126.965408,E,399,7,1,17,-0.352941,37.554108,126.965408,적음
30,32,37.556416,126.969193,E,442,2,1,20,-0.050000,37.556416,126.969193,적음
31,44,37.564430,127.009956,A,476,3,2,10,-0.100000,37.564430,127.009956,적음
32,49,37.555367,126.968643,E,826,16,5,22,-0.500000,37.555367,126.968643,적음
33,56,37.567017,126.976837,D,4768,26,19,12,-0.583333,37.567017,126.976837,적음
34,62,37.561573,126.968491,E,4782,2,1,10,-0.100000,37.561573,126.968491,적음
35,66,37.562527,126.998314,C,4792,8,6,10,-0.200000,37.562527,126.998314,적음

#  데이터 불러와서 D 군집만 추출

In [14]:
df = df[df.cluster == 'D']
df = df.sort_values(by='(반납-대여)/거치대수', ascending=False)
df

,key_0,위도_x,경도_x,cluster,대여소번호,대여수,반납수,거치대수,(반납-대여)/거치대수,위도_y,경도_y,group
1,1,37.568878,126.977470,D,310,5,13,8,1.000000,37.568878,126.977470,많음
24,68,37.566471,126.979256,D,4796,6,11,10,0.500000,37.566471,126.979256,많음
17,39,37.560360,126.982651,D,471,5,9,10,0.400000,37.560360,126.982651,많음
6,6,37.561340,126.980400,D,324,5,9,12,0.333333,37.561340,126.980400,많음
16,36,37.562214,126.980865,D,467,2,6,16,0.250000,37.562214,126.980866,많음
33,56,37.567017,126.976837,D,4768,26,19,12,-0.583333,37.567017,126.976837,적음

In [15]:
df = df.reset_index()
df['node_num'] = range(1,7)
df

,index,key_0,위도_x,경도_x,cluster,대여소번호,대여수,반납수,거치대수,(반납-대여)/거치대수,위도_y,경도_y,group,node_num
0,1,1,37.568878,126.977470,D,310,5,13,8,1.000000,37.568878,126.977470,많음,1
1,24,68,37.566471,126.979256,D,4796,6,11,10,0.500000,37.566471,126.979256,많음,2
2,17,39,37.560360,126.982651,D,471,5,9,10,0.400000,37.560360,126.982651,많음,3
3,6,6,37.561340,126.980400,D,324,5,9,12,0.333333,37.561340,126.980400,많음,4
4,16,36,37.562214,126.980865,D,467,2,6,16,0.250000,37.562214,126.980866,많음,5
5,33,56,37.567017,126.976837,D,4768,26,19,12,-0.583333,37.567017,126.976837,적음,6

# 대여소간 거리 계산해서 가중치 행렬 만들기

In [16]:
from haversine import haversine

dist = np.zeros((6,6))
for i in range(6):
    for j in range(i+1,6):
        distance = haversine((df.위도_x[i],df.경도_x[i]), (df.위도_x[j],df.경도_x[j]), unit='km')
        dist[i][j] = distance
        dist[j][i] = distance
df_dist = pd.DataFrame(dist)
df_dist

          0         1         2         3         4         5
0  0.000000  0.310481  1.051496  0.877046  0.799173  0.214389
1  0.310481  0.000000  0.742504  0.579365  0.494187  0.221624
2  1.051496  0.742504  0.000000  0.226366  0.259348  0.900251
3  0.877046  0.579365  0.226366  0.000000  0.105444  0.704982
4  0.799173  0.494187  0.259348  0.105444  0.000000  0.641296
5  0.214389  0.221624  0.900251  0.704982  0.641296  0.000000

# tsp

In [17]:
import copy

In [18]:
data = [1,2,3,4,5,6]
n = len(data)
all_sets = []
g = {}
p = []
node = [1]

In [19]:
def main():
    for x in range(1, n):
        g[x + 1, ()] = dist[x][0]

    get_minimum(1, (2,3,4,5,6))

    print('\n\nSolution to TSP: {1, ', end='')
    solution = p.pop()
    print(solution[1][0], end=', ')
    node.append(solution[1][0])
    for x in range(n - 2):
        for new_solution in p:
            if tuple(solution[1]) == new_solution[0]:
                solution = new_solution
                print(solution[1][0], end=', ')
                node.append(solution[1][0])
                break
    print('1}')
    return

In [20]:
def get_minimum(k, a):
    if (k, a) in g:
        # Already calculated Set g[%d, (%s)]=%d' % (k, str(a), g[k, a]))
        return g[k, a]

    values = []
    all_min = []
    for j in a:
        set_a = copy.deepcopy(list(a))
        set_a.remove(j)
        all_min.append([j, tuple(set_a)])
        result = get_minimum(j, tuple(set_a))
        values.append(dist[k-1][j-1] + result)

    # get minimun value from set as optimal solution for
    g[k, a] = min(values)
    p.append(((k, a), all_min[values.index(g[k, a])]))

    return g[k, a]

In [21]:
main()

Solution to TSP: {1, 2, 5, 3, 4, 6, 1}

# 총거리 구하기

In [22]:
node.append(1)

dist_total = 0
for i in range(len(node)-1):
    dist_total += df_dist[node[i]-1][node[i+1]-1]
dist_total

2.2097527379524293

In [23]:
len(df)

6

In [24]:
node

[1, 2, 5, 3, 4, 6, 1]