In [13]:
import numpy as np
import pandas as pd

In [14]:
kmeans = pd.read_csv("./k_means(중구, 23, 17-21, k=4)_n.csv")
diff = pd.read_csv("./중구대여반납_거치대23_group_17_21.csv")

df = pd.merge(kmeans, diff, how='left', left_on=kmeans.index, right_on=diff.index)
df

,key_0,위도_x,경도_x,cluster,대여소번호,대여수,반납수,거치대수,(반납-대여)/거치대수,위도_y,경도_y,group
0,15,37.560474,127.014076,B,374,21,23,12,0.166667,37.560474,127.014076,많음
1,19,37.565849,127.016403,B,383,36,37,19,0.052632,37.565849,127.016403,많음
2,20,37.559780,126.968506,D,384,4,5,12,0.083333,37.559780,126.968506,많음
3,25,37.554108,126.965408,D,399,8,9,17,0.058824,37.554108,126.965408,많음
4,31,37.556862,126.975617,C,435,4,5,12,0.083333,37.556862,126.975617,많음
5,32,37.559891,126.971497,C,441,6,7,15,0.066667,37.559891,126.971497,많음
6,33,37.556416,126.969193,D,442,3,6,20,0.150000,37.556416,126.969193,많음
7,44,37.567650,127.011810,B,475,10,12,16,0.125000,37.567650,127.011810,많음
8,48,37.554321,127.010704,A,480,6,7,8,0.125000,37.554321,127.010704,많음
9,49,37.567032,127.015793,B,481,13,16,16,0.187500,37.567032,127.015793,많음
10,51,37.547585,127.006439,A,483,1,2,16,0.062500,37.547585,127.006439,많음
11,53,37.556770,126.973198,C,485,20,21,10,0.100000,37.556770,126.973198,많음
12,54,37.555367,126.968643,D,826,18,27,22,0.409091,37.555367,126.968643,많음
13,58,37.556644,126.973640,C,4760,1,3,10,0.200000,37.556644,126.973640,많음
14,62,37.560246,126.968780,D,4766,2,3,18,0.055556,37.560246,126.968780,많음
15,0,37.568050,126.969231,D,300,16,10,9,-0.666667,37.568050,126.969231,적음
16,1,37.568878,126.977470,C,310,35,16,8,-2.375000,37.568878,126.977470,적음
17,3,37.566223,126.983589,B,320,21,10,17,-0.647059,37.566223,126.983589,적음
18,4,37.565464,126.984139,B,321,24,8,17,-0.941176,37.565464,126.984139,적음
19,6,37.561340,126.980400,C,324,14,8,12,-0.500000,37.561340,126.980400,적음
20,12,37.563229,126.974838,C,370,42,19,24,-0.958333,37.563229,126.974838,적음
21,17,37.563866,127.002747,A,380,14,9,10,-0.500000,37.563866,127.002747,적음
22,18,37.555199,127.010048,A,382,13,9,9,-0.444444,37.555199,127.010048,적음
23,21,37.566994,127.003464,A,387,27,8,12,-1.583333,37.566994,127.003464,적음
24,24,37.566559,126.992439,B,398,36,24,10,-1.200000,37.566559,126.992439,적음
25,36,37.565842,126.979813,C,466,20,1,20,-0.950000,37.565842,126.979813,적음
26,38,37.559231,126.980141,C,469,11,2,16,-0.562500,37.559231,126.980141,적음
27,40,37.560360,126.982651,C,471,13,8,10,-0.500000,37.560360,126.982651,적음
28,55,37.567616,126.987244,B,3013,28,9,10,-1.900000,37.567616,126.987244,적음
29,56,37.558914,126.964859,D,4752,10,5,7,-0.714286,37.558914,126.964859,적음
30,63,37.567017,126.976837,C,4768,38,31,12,-0.583333,37.567017,126.976837,적음
31,71,37.566898,126.987740,B,4785,18,4,8,-1.750000,37.566898,126.987740,적음
32,75,37.566471,126.979256,C,4796,20,10,10,-1.000000,37.566471,126.979256,적음

#  데이터 불러와서 B 군집만 추출

In [15]:
df = df[df.cluster == 'B']
df = df.sort_values(by='(반납-대여)/거치대수', ascending=False)
df

,key_0,위도_x,경도_x,cluster,대여소번호,대여수,반납수,거치대수,(반납-대여)/거치대수,위도_y,경도_y,group
9,49,37.567032,127.015793,B,481,13,16,16,0.187500,37.567032,127.015793,많음
0,15,37.560474,127.014076,B,374,21,23,12,0.166667,37.560474,127.014076,많음
7,44,37.567650,127.011810,B,475,10,12,16,0.125000,37.567650,127.011810,많음
1,19,37.565849,127.016403,B,383,36,37,19,0.052632,37.565849,127.016403,많음
17,3,37.566223,126.983589,B,320,21,10,17,-0.647059,37.566223,126.983589,적음
18,4,37.565464,126.984139,B,321,24,8,17,-0.941176,37.565464,126.984139,적음
24,24,37.566559,126.992439,B,398,36,24,10,-1.200000,37.566559,126.992439,적음
31,71,37.566898,126.987740,B,4785,18,4,8,-1.750000,37.566898,126.987740,적음
28,55,37.567616,126.987244,B,3013,28,9,10,-1.900000,37.567616,126.987244,적음

In [16]:
df = df.reset_index()
df['node_num'] = range(1,10)
df

,index,key_0,위도_x,경도_x,cluster,대여소번호,대여수,반납수,거치대수,(반납-대여)/거치대수,위도_y,경도_y,group,node_num
0,9,49,37.567032,127.015793,B,481,13,16,16,0.187500,37.567032,127.015793,많음,1
1,0,15,37.560474,127.014076,B,374,21,23,12,0.166667,37.560474,127.014076,많음,2
2,7,44,37.567650,127.011810,B,475,10,12,16,0.125000,37.567650,127.011810,많음,3
3,1,19,37.565849,127.016403,B,383,36,37,19,0.052632,37.565849,127.016403,많음,4
4,17,3,37.566223,126.983589,B,320,21,10,17,-0.647059,37.566223,126.983589,적음,5
5,18,4,37.565464,126.984139,B,321,24,8,17,-0.941176,37.565464,126.984139,적음,6
6,24,24,37.566559,126.992439,B,398,36,24,10,-1.200000,37.566559,126.992439,적음,7
7,31,71,37.566898,126.987740,B,4785,18,4,8,-1.750000,37.566898,126.987740,적음,8
8,28,55,37.567616,126.987244,B,3013,28,9,10,-1.900000,37.567616,126.987244,적음,9

# 대여소간 거리 계산해서 가중치 행렬 만들기

In [17]:
from haversine import haversine

dist = np.zeros((9,9))
for i in range(9):
    for j in range(i+1,9):
        distance = haversine((df.위도_x[i],df.경도_x[i]), (df.위도_x[j],df.경도_x[j]), unit='km')
        dist[i][j] = distance
        dist[j][i] = distance
df_dist = pd.DataFrame(dist)
df_dist

,0,1,2,3,4,5,6,7,8
0,0.000000,0.744692,0.357679,0.142072,2.839801,2.795418,2.059012,2.472601,2.517089
1,0.744692,0.000000,0.822490,0.631878,2.762172,2.696482,2.023569,2.428769,2.494792
2,0.357679,0.822490,0.000000,0.451614,2.492401,2.451026,1.711619,2.123175,2.165230
3,0.142072,0.631878,0.451614,0.000000,2.892489,2.844113,2.113620,2.529059,2.577555
4,2.839801,2.762172,2.492401,2.892489,0.000000,0.097309,0.780927,0.373435,0.357378
5,2.795418,2.696482,2.451026,2.844113,0.097309,0.000000,0.741683,0.355215,0.363508
6,2.059012,2.023569,1.711619,2.113620,0.780927,0.741683,0.000000,0.415939,0.472762
7,2.472601,2.428769,2.123175,2.529059,0.373435,0.355215,0.415939,0.000000,0.090937
8,2.517089,2.494792,2.165230,2.577555,0.357378,0.363508,0.472762,0.090937,0.000000

# tsp

In [18]:
import copy

In [19]:
data = [1,2,3,4,5,6,7,8,9]
n = len(data)
all_sets = []
g = {}
p = []
node = [1]

In [20]:
def main():
    for x in range(1, n):
        g[x + 1, ()] = dist[x][0]

    get_minimum(1, (2,3,4,5,6,7,8,9))

    print('\n\nSolution to TSP: {1, ', end='')
    solution = p.pop()
    print(solution[1][0], end=', ')
    node.append(solution[1][0])
    for x in range(n - 2):
        for new_solution in p:
            if tuple(solution[1]) == new_solution[0]:
                solution = new_solution
                print(solution[1][0], end=', ')
                node.append(solution[1][0])
                break
    print('1}')
    return

In [21]:
def get_minimum(k, a):
    if (k, a) in g:
        # Already calculated Set g[%d, (%s)]=%d' % (k, str(a), g[k, a]))
        return g[k, a]

    values = []
    all_min = []
    for j in a:
        set_a = copy.deepcopy(list(a))
        set_a.remove(j)
        all_min.append([j, tuple(set_a)])
        result = get_minimum(j, tuple(set_a))
        values.append(dist[k-1][j-1] + result)

    # get minimun value from set as optimal solution for
    g[k, a] = min(values)
    p.append(((k, a), all_min[values.index(g[k, a])]))

    return g[k, a]

In [22]:
main()

Solution to TSP: {1, 3, 7, 8, 9, 5, 6, 2, 4, 1}

# 총거리 구하기

In [23]:
node.append(1)

dist_total = 0
for i in range(len(node)-1):
    dist_total += df_dist[node[i]-1][node[i+1]-1]
dist_total

6.501292209278109

In [24]:
len(df)

9

In [25]:
node

[1, 3, 7, 8, 9, 5, 6, 2, 4, 1]