In [12]:
import numpy as np
import pandas as pd

In [13]:
kmeans = pd.read_csv("./k_means(중구, 24, 6-10, k=2)_n.csv")
diff = pd.read_csv("./중구대여반납_거치대24_group_6_10.csv")

df = pd.merge(kmeans, diff, how='left', left_on=kmeans.index, right_on=diff.index)
df

,key_0,위도_x,경도_x,cluster,대여소번호,대여수,반납수,거치대수,(반납-대여)/거치대수,위도_y,경도_y,group
0,0,37.568050,126.969231,A,300,8,19,9,1.222222,37.568050,126.969231,많음
1,1,37.568878,126.977470,A,310,2,13,8,1.375000,37.568878,126.977470,많음
2,6,37.565990,126.987793,A,332,1,12,5,2.200000,37.565990,126.987793,많음
3,8,37.569183,127.009880,B,346,4,20,12,1.333333,37.569183,127.009880,많음
4,10,37.563229,126.974838,A,370,3,41,24,1.583333,37.563229,126.974838,많음
5,14,37.563866,127.002747,B,380,3,13,10,1.000000,37.563866,127.002747,많음
6,19,37.561390,126.995354,B,390,3,17,12,1.166667,37.561390,126.995354,많음
7,26,37.560154,126.974106,A,445,4,13,10,0.900000,37.560154,126.974106,많음
8,37,37.567017,126.976837,A,4768,4,19,12,1.250000,37.567017,126.976837,많음
9,45,37.566471,126.979256,A,4796,3,11,10,0.800000,37.566471,126.979256,많음
10,9,37.565331,127.007843,A,347,1,6,20,0.250000,37.565331,127.007843,적음
11,11,37.554295,127.011200,A,372,4,5,12,0.083333,37.554295,127.011200,적음
12,12,37.560474,127.014076,A,374,7,10,12,0.250000,37.560474,127.014076,적음
13,16,37.565849,127.016403,A,383,5,10,19,0.263158,37.565849,127.016403,적음
14,20,37.566559,126.992439,B,398,4,6,10,0.200000,37.566559,126.992439,적음
15,21,37.554108,126.965408,B,399,4,1,17,-0.176471,37.554108,126.965408,적음
16,23,37.570900,127.019524,A,431,16,13,15,-0.200000,37.570900,127.019524,적음
17,24,37.566345,126.982292,B,433,6,9,12,0.250000,37.566345,126.982292,적음
18,25,37.559891,126.971497,B,441,2,6,15,0.266667,37.559891,126.971497,적음
19,28,37.564159,126.979485,B,468,3,5,10,0.200000,37.564159,126.979485,적음
20,30,37.566299,127.008492,A,474,1,7,30,0.200000,37.566299,127.008492,적음
21,31,37.567650,127.011810,A,475,3,6,16,0.187500,37.567650,127.011810,적음
22,32,37.564430,127.009956,A,476,1,2,10,0.100000,37.564430,127.009956,적음
23,33,37.559376,127.006027,A,479,3,2,13,-0.076923,37.559376,127.006027,적음
24,34,37.556770,126.973198,B,485,3,3,10,0.000000,37.556770,126.973198,적음
25,35,37.555367,126.968643,B,826,5,5,22,0.000000,37.555367,126.968643,적음
26,36,37.560246,126.968780,B,4766,1,2,18,0.055556,37.560246,126.968780,적음
27,40,37.560055,126.980942,B,4776,1,2,10,0.100000,37.560055,126.980942,적음
28,41,37.561573,126.968491,B,4782,2,1,10,-0.100000,37.561573,126.968491,적음
29,42,37.564590,126.990768,B,4784,1,3,10,0.200000,37.564590,126.990768,적음

#  데이터 불러와서 A 군집만 추출

In [14]:
df = df[df.cluster == 'A']
df = df.sort_values(by='(반납-대여)/거치대수', ascending=False)
df

,key_0,위도_x,경도_x,cluster,대여소번호,대여수,반납수,거치대수,(반납-대여)/거치대수,위도_y,경도_y,group
2,6,37.565990,126.987793,A,332,1,12,5,2.200000,37.565990,126.987793,많음
4,10,37.563229,126.974838,A,370,3,41,24,1.583333,37.563229,126.974838,많음
1,1,37.568878,126.977470,A,310,2,13,8,1.375000,37.568878,126.977470,많음
8,37,37.567017,126.976837,A,4768,4,19,12,1.250000,37.567017,126.976837,많음
0,0,37.568050,126.969231,A,300,8,19,9,1.222222,37.568050,126.969231,많음
7,26,37.560154,126.974106,A,445,4,13,10,0.900000,37.560154,126.974106,많음
9,45,37.566471,126.979256,A,4796,3,11,10,0.800000,37.566471,126.979256,많음
13,16,37.565849,127.016403,A,383,5,10,19,0.263158,37.565849,127.016403,적음
10,9,37.565331,127.007843,A,347,1,6,20,0.250000,37.565331,127.007843,적음
12,12,37.560474,127.014076,A,374,7,10,12,0.250000,37.560474,127.014076,적음
20,30,37.566299,127.008492,A,474,1,7,30,0.200000,37.566299,127.008492,적음
21,31,37.567650,127.011810,A,475,3,6,16,0.187500,37.567650,127.011810,적음
22,32,37.564430,127.009956,A,476,1,2,10,0.100000,37.564430,127.009956,적음
11,11,37.554295,127.011200,A,372,4,5,12,0.083333,37.554295,127.011200,적음
23,33,37.559376,127.006027,A,479,3,2,13,-0.076923,37.559376,127.006027,적음
16,23,37.570900,127.019524,A,431,16,13,15,-0.200000,37.570900,127.019524,적음

In [15]:
df = df.reset_index()
df['node_num'] = range(1,17)
df

,index,key_0,위도_x,경도_x,cluster,대여소번호,대여수,반납수,거치대수,(반납-대여)/거치대수,위도_y,경도_y,group,node_num
0,2,6,37.565990,126.987793,A,332,1,12,5,2.200000,37.565990,126.987793,많음,1
1,4,10,37.563229,126.974838,A,370,3,41,24,1.583333,37.563229,126.974838,많음,2
2,1,1,37.568878,126.977470,A,310,2,13,8,1.375000,37.568878,126.977470,많음,3
3,8,37,37.567017,126.976837,A,4768,4,19,12,1.250000,37.567017,126.976837,많음,4
4,0,0,37.568050,126.969231,A,300,8,19,9,1.222222,37.568050,126.969231,많음,5
5,7,26,37.560154,126.974106,A,445,4,13,10,0.900000,37.560154,126.974106,많음,6
6,9,45,37.566471,126.979256,A,4796,3,11,10,0.800000,37.566471,126.979256,많음,7
7,13,16,37.565849,127.016403,A,383,5,10,19,0.263158,37.565849,127.016403,적음,8
8,10,9,37.565331,127.007843,A,347,1,6,20,0.250000,37.565331,127.007843,적음,9
9,12,12,37.560474,127.014076,A,374,7,10,12,0.250000,37.560474,127.014076,적음,10
10,20,30,37.566299,127.008492,A,474,1,7,30,0.200000,37.566299,127.008492,적음,11
11,21,31,37.567650,127.011810,A,475,3,6,16,0.187500,37.567650,127.011810,적음,12
12,22,32,37.564430,127.009956,A,476,1,2,10,0.100000,37.564430,127.009956,적음,13
13,11,11,37.554295,127.011200,A,372,4,5,12,0.083333,37.554295,127.011200,적음,14
14,23,33,37.559376,127.006027,A,479,3,2,13,-0.076923,37.559376,127.006027,적음,15
15,16,23,37.570900,127.019524,A,431,16,13,15,-0.200000,37.570900,127.019524,적음,16

# 대여소간 거리 계산해서 가중치 행렬 만들기

In [16]:
from haversine import haversine

dist = np.zeros((16,16))
for i in range(16):
    for j in range(i+1,16):
        distance = haversine((df.위도_x[i],df.경도_x[i]), (df.위도_x[j],df.경도_x[j]), unit='km')
        dist[i][j] = distance
        dist[j][i] = distance
df_dist = pd.DataFrame(dist)
df_dist

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0.000000,1.182413,0.964807,0.972344,1.651996,1.369906,0.754362,2.521725,1.768717,2.396481,1.824664,2.124863,1.961168,2.438909,1.767521,2.849395
1,1.182413,0.000000,0.669671,0.456569,0.729210,0.347929,0.530650,3.675130,2.918441,3.472113,2.985796,3.295573,3.098245,3.355614,2.782312,4.029777
2,0.964807,0.669671,0.000000,0.214389,0.732025,1.014406,0.310481,3.447922,2.705879,3.359050,2.749104,3.029671,2.905660,3.386560,2.729815,3.713143
3,0.972344,0.456569,0.214389,0.000000,0.680199,0.800169,0.221624,3.489700,2.739236,3.361953,2.791092,3.083241,2.933235,3.342979,2.709527,3.786885
4,1.651996,0.729210,0.732025,0.680199,0.000000,0.977548,0.900860,4.164879,3.416628,4.041499,3.465824,3.753092,3.612010,4.003116,3.383701,4.443868
5,1.369906,0.347929,1.014406,0.800169,0.977548,0.000000,0.836338,3.781604,3.028888,3.523398,3.106913,3.426258,3.195567,3.334108,2.815085,4.177634
6,0.754362,0.530650,0.310481,0.221624,0.900860,0.836338,0.000000,3.274865,2.522848,3.140746,2.576870,2.872280,2.715447,3.124368,2.488111,3.583047
7,2.521725,3.675130,3.447922,3.489700,4.164879,3.781604,3.274865,0.000000,0.756693,0.631878,0.699122,0.451614,0.589723,1.364233,1.163869,0.625332
8,1.768717,2.918441,2.705879,2.739236,3.416628,3.028888,2.522848,0.756693,0.000000,0.770341,0.121963,0.434490,0.211470,1.262313,0.681208,1.201403
9,2.396481,3.472113,3.359050,3.361953,4.041499,3.523398,3.140746,0.631878,0.770341,0.000000,0.813537,0.822490,0.570395,0.732444,0.719929,1.254765
10,1.824664,2.985796,2.749104,2.791092,3.465824,3.106913,2.576870,0.699122,0.121963,0.813537,0.000000,0.328802,0.244685,1.356062,0.799934,1.098682
11,2.124863,3.295573,3.029671,3.083241,3.753092,3.426258,2.872280,0.451614,0.434490,0.822490,0.328802,0.000000,0.393531,1.486012,1.051806,0.769904
12,1.961168,3.098245,2.905660,2.933235,3.612010,3.195567,2.715447,0.589723,0.211470,0.570395,0.244685,0.393531,0.000000,1.132353,0.660174,1.108406
13,2.438909,3.355614,3.386560,3.342979,4.003116,3.334108,3.124368,1.364233,1.262313,0.732444,1.356062,1.486012,1.132353,0.000000,0.726048,1.986855
14,1.767521,2.782312,2.729815,2.709527,3.383701,2.815085,2.488111,1.163869,0.681208,0.719929,0.799934,1.051806,0.660174,0.726048,0.000000,1.748473
15,2.849395,4.029777,3.713143,3.786885,4.443868,4.177634,3.583047,0.625332,1.201403,1.254765,1.098682,0.769904,1.108406,1.986855,1.748473,0.000000

# tsp

In [17]:
import copy

In [18]:
data = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
n = len(data)
all_sets = []
g = {}
p = []
node = [1]

In [19]:
def main():
    for x in range(1, n):
        g[x + 1, ()] = dist[x][0]

    get_minimum(1, (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16))

    print('\n\nSolution to TSP: {1, ', end='')
    solution = p.pop()
    print(solution[1][0], end=', ')
    node.append(solution[1][0])
    for x in range(n - 2):
        for new_solution in p:
            if tuple(solution[1]) == new_solution[0]:
                solution = new_solution
                print(solution[1][0], end=', ')
                node.append(solution[1][0])
                break
    print('1}')
    return

In [20]:
def get_minimum(k, a):
    if (k, a) in g:
        # Already calculated Set g[%d, (%s)]=%d' % (k, str(a), g[k, a]))
        return g[k, a]

    values = []
    all_min = []
    for j in a:
        set_a = copy.deepcopy(list(a))
        set_a.remove(j)
        all_min.append([j, tuple(set_a)])
        result = get_minimum(j, tuple(set_a))
        values.append(dist[k-1][j-1] + result)

    # get minimun value from set as optimal solution for
    g[k, a] = min(values)
    p.append(((k, a), all_min[values.index(g[k, a])]))

    return g[k, a]

In [21]:
main()

Solution to TSP: {1, 9, 11, 13, 12, 16, 8, 10, 14, 15, 6, 2, 5, 3, 4, 7, 1}

# 총거리 구하기

In [22]:
node.append(1)

dist_total = 0
for i in range(len(node)-1):
    dist_total += df_dist[node[i]-1][node[i+1]-1]
dist_total

11.82912585719475

In [23]:
len(df)

16

In [24]:
node

[1, 9, 11, 13, 12, 16, 8, 10, 14, 15, 6, 2, 5, 3, 4, 7, 1]